"""Add title column

Revision ID: cf635636da2f
Revises: 
Create Date: 2025-07-19 00:28:19.321520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf635636da2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('mood_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DATETIME(), nullable=True))
        batch_op.alter_column('mood_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('date')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
